In [17]:
import pandas as pd

In [18]:
hotel_df = pd.read_csv('hotel_bookings.csv')

In [19]:
hotel_df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,1/7/2015
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,1/7/2015
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2/7/2015
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2/7/2015
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,3/7/2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,6/9/2017
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,7/9/2017
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,7/9/2017
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,7/9/2017
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,7/9/2017

In [20]:
hotel_df.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
dtype: object

In [33]:
missing_values = hotel_df.isnull().sum()
missing_percentage = (missing_values / len(hotel_df)) * 100

missing_data = pd.DataFrame({'Missing_Values': missing_values, 'Percentage (%)': missing_percentage})
missing_data

                             Missing_Values  Percentage (%)
hotel                                     0             0.0
is_canceled                               0             0.0
arrival_date_week_number                  0             0.0
adults                                    0             0.0
children                                  0             0.0
babies                                    0             0.0
meal                                      0             0.0
country                                   0             0.0
market_segment                            0             0.0
distribution_channel                      0             0.0
is_repeated_guest                         0             0.0
reserved_room_type                        0             0.0
booking_changes                           0             0.0
deposit_type                              0             0.0
days_in_waiting_list                      0             0.0
customer_type                             0             0.0
required_car_parking_spaces               0             0.0
total_of_special_requests                 0             0.0
reservation_status                        0             0.0
Total Guests                              0             0.0
date                                      0             0.0

In [22]:
hotel_df = hotel_df.drop(columns=['company','agent','adr','assigned_room_type', 'previous_cancellations', 'previous_bookings_not_canceled', 'lead_time', 'stays_in_weekend_nights', 'stays_in_week_nights'])

In [23]:
hotel_df['country'] = hotel_df['country'].fillna('Other')
hotel_df['children'] = hotel_df['children'].fillna(0)

In [24]:
hotel_df.dtypes

hotel                           object
is_canceled                      int64
arrival_date_year                int64
arrival_date_month              object
arrival_date_week_number         int64
arrival_date_day_of_month        int64
adults                           int64
children                       float64
babies                           int64
meal                            object
country                         object
market_segment                  object
distribution_channel            object
is_repeated_guest                int64
reserved_room_type              object
booking_changes                  int64
deposit_type                    object
days_in_waiting_list             int64
customer_type                   object
required_car_parking_spaces      int64
total_of_special_requests        int64
reservation_status              object
reservation_status_date         object
dtype: object

In [25]:
hotel_df['Total Guests'] = hotel_df['adults'] + hotel_df['children'] + hotel_df['babies']

In [26]:
hotel_df.columns

Index(['hotel', 'is_canceled', 'arrival_date_year', 'arrival_date_month',
       'arrival_date_week_number', 'arrival_date_day_of_month', 'adults',
       'children', 'babies', 'meal', 'country', 'market_segment',
       'distribution_channel', 'is_repeated_guest', 'reserved_room_type',
       'booking_changes', 'deposit_type', 'days_in_waiting_list',
       'customer_type', 'required_car_parking_spaces',
       'total_of_special_requests', 'reservation_status',
       'reservation_status_date', 'Total Guests'],
      dtype='object')

In [27]:
hotel_df.shape

(119390, 24)

In [29]:
hotel_df["date"] = pd.to_datetime(hotel_df["arrival_date_year"].astype(str) + '-' + hotel_df["arrival_date_month"].astype(str) + '-' + hotel_df["arrival_date_day_of_month"].astype(str))

In [31]:
hotel_df = hotel_df.drop(columns=['reservation_status_date', 'arrival_date_year', 'arrival_date_month', 'arrival_date_day_of_month'])

In [32]:
hotel_df.shape

(119390, 21)