In [1]:
import pandas as pd

In [2]:
inventory_df = pd.read_csv('retail_store_inventory.csv')

In [3]:
inventory_df

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73095,2024-01-01,S005,P0016,Furniture,East,96,8,127,18.46,73.73,20,Snowy,0,72.45,Winter
73096,2024-01-01,S005,P0017,Toys,North,313,51,101,48.43,82.57,10,Cloudy,0,83.78,Autumn
73097,2024-01-01,S005,P0018,Clothing,West,278,36,151,39.65,11.11,10,Rainy,0,10.91,Winter
73098,2024-01-01,S005,P0019,Toys,East,374,264,21,270.52,53.14,20,Rainy,0,55.80,Spring
73099,2024-01-01,S005,P0020,Groceries,East,117,6,165,2.33,78.39,20,Rainy,1,79.52,Spring

In [4]:
inventory_df.dtypes

Date                   object
Store ID               object
Product ID             object
Category               object
Region                 object
Inventory Level         int64
Units Sold              int64
Units Ordered           int64
Demand Forecast       float64
Price                 float64
Discount                int64
Weather Condition      object
Holiday/Promotion       int64
Competitor Pricing    float64
Seasonality            object
dtype: object

In [5]:
print('Number of Rows in the dataset - ', inventory_df.shape[0])
print('Number of Columns in the dataset - ', inventory_df.shape[1])

Number of Rows in the dataset -  73100
Number of Columns in the dataset -  15

In [8]:
missing_values = inventory_df.isnull().sum()
missing_percentage = (missing_values / len(missing_values)) % 100

missing_data = pd.DataFrame({'Missing Values' : missing_values, 'Percentage (%)': missing_percentage})
missing_data

                    Missing Values  Percentage (%)
Date                             0             0.0
Store ID                         0             0.0
Product ID                       0             0.0
Category                         0             0.0
Region                           0             0.0
Inventory Level                  0             0.0
Units Sold                       0             0.0
Units Ordered                    0             0.0
Demand Forecast                  0             0.0
Price                            0             0.0
Discount                         0             0.0
Weather Condition                0             0.0
Holiday/Promotion                0             0.0
Competitor Pricing               0             0.0
Seasonality                      0             0.0

In [11]:
inventory_df[]

2

In [ ]:
from sqlalchemy import create_engine

server = 'DESKTOP-5V2R0U0\ADMIN'
database = 'inventory_supplychain'

conn_str = f'mssql+pyodbc://@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes'

engine = create_engine(conn_str)
inventory_df.to_sql('Inventory', engine, if_exists='replace', index='False')